### ISSUE TITLE
Store group chats in DB and populate FoodHubFragment with adapter

### ISSUE THREAD

**Issue by vivfang** [oledibefrancis/CareerMatch#1]
https://github.com/oledibefrancis/CareerMatch/blob/567c26356d64e42bec2c868c6cece1d194a112ce/app/src/main/java/com/example/foodmates/fragments/FoodHubFragment.java#L54

I think we could try to store all the different group chats in the database, instead of hard coding them here. Then we can query for them and populate this fragment with a group chat adapter, similar to what you're doing in HomeFragment.

**Comment by oledibefrancis** [comment]
Done
