### ISSUE TITLE
Consolidate BreakFastActivity and ChatActivity

### ISSUE THREAD

**Issue by vivfang** [oledibefrancis/CareerMatch#2]
https://github.com/oledibefrancis/CareerMatch/blob/567c26356d64e42bec2c868c6cece1d194a112ce/app/src/main/java/com/example/foodmates/Activities/BreakFastActivity.java#L134

BreakFastActivity and ChatActivity look pretty similar. Maybe we can consolidate them into one activity. We can pass information, such as the keys for querying, from the intent in the onClickListeners here: https://github.com/oledibefrancis/CareerMatch/blob/567c26356d64e42bec2c868c6cece1d194a112ce/app/src/main/java/com/example/foodmates/fragments/FoodHubFragment.java#L60.

**Comment by oledibefrancis** [comment]
Done
